// ══════════════════════════════════════════════
// STUDY DATA — Single source of truth
// Privacy-scrubbed: no school names, professor names, or class numbers
// ══════════════════════════════════════════════

window.STUDY_DATA = {
  siteName: 'Study with Tiago',
  youtubeChannel: 'https://www.youtube.com/@life-ofstudy',
  gumroadUrl: 'https://medpro3.gumroad.com/l/wcoda',
  gumroadOverlay: 'https://medpro3.gumroad.com/l/wcoda',

  videos: [
    {
      id: 'deck3',
      title: 'Diabetes Drugs Made Simple',
      label: 'Deck 3 — Diabetes',
      color: '#2B8A3E',
      status: 'uploaded',
      statusText: 'UPLOADED',
      youtubeId: 'dL9bcmea9Mw',
      questionCount: '12-13',
      chapter: 'Chapter 41',
      subtitle: '38 slides • ~12-13 exam questions • Chapter 41',
      timestamps: [
        ['00:00','Intro — Why this chapter matters'],
        ['01:00','Type 1 vs Type 2 Diabetes'],
        ['02:00','Rapid-Acting Insulin (Lispro)'],
        ['03:30','Regular Insulin — ONLY one for IV'],
        ['04:30','NPH Insulin — ONLY cloudy insulin'],
        ['05:30','Glargine (Lantus) — no peak, never mix'],
        ['06:30','Quiz: which insulin is cloudy?'],
        ['07:00','Clear Before Cloudy mixing rule'],
        ['07:30','Somogyi vs Dawn Phenomenon'],
        ['08:30','15-15 Rule + TIRED mnemonic'],
        ['09:30','Metformin — first-line, IV contrast rule'],
        ['11:00','Quiz: metformin + CT contrast'],
        ['11:30','Sulfonylureas — hypo risk, weight gain'],
        ['12:30','Acarbose — glucose tabs ONLY for hypo'],
        ['13:30','Quiz: acarbose + hypo treatment'],
        ['14:00','SGLT-2 Inhibitors — euglycemic DKA'],
        ['15:00','GLP-1 Agonists (Ozempic) — BBW thyroid'],
        ['15:45','DPP-4 Inhibitors (Sitagliptin)'],
        ['16:15','MSG mnemonic for weight loss'],
        ['16:30','Quiz: obese T2DM drug choice'],
        ['17:00','Pramlintide — cut insulin 50%'],
        ['17:45','Quiz: pramlintide insulin dose'],
        ['18:15','DKA vs HHS — ketones = differentiator'],
        ['19:00','K+ ≥ 3.3 before insulin (FKI-D)'],
        ['19:45','Glucagon — severe hypo rescue'],
        ['20:15','Quiz: DKA + K+ 3.1 — what first?'],
        ['20:45','Sick Day Rule — never stop insulin T1'],
      ],
      said: [
        { name: 'Rapid-Acting Insulin (Lispro)', ts: '02:00', detail: '15 min onset, give before meals' },
        { name: 'Short-Acting (Regular) — ONLY IV insulin', ts: '03:30', detail: 'Clear, 30-60 min onset' },
        { name: 'Intermediate (NPH) — ONLY cloudy', ts: '04:30', detail: 'Wide 4-12h peak' },
        { name: 'Long-Acting (Glargine) — NEVER mix', ts: '05:30', detail: 'No peak, basal insulin' },
        { name: 'Premixed 70/30 and 75/25', ts: '06:30', detail: 'NPH is always bigger number' },
        { name: 'Mixing: Clear Before Cloudy', ts: '07:00', detail: 'Draw regular first, then NPH' },
        { name: 'Somogyi vs Dawn Phenomenon', ts: '07:30', detail: '3 AM glucose check differentiates' },
        { name: 'Hypoglycemia (TIRED) + 15-15 Rule', ts: '08:30', detail: '15g carbs, wait 15 min, recheck' },
        { name: 'Beta-Blocker Masking', ts: '08:30', detail: 'Diaphoresis = only reliable sign' },
        { name: 'Metformin — 1st line T2DM', ts: '09:30', detail: 'Hold 48h for IV contrast, lactic acidosis' },
        { name: 'Sulfonylureas (all 5 named)', ts: '11:30', detail: 'Hypo risk, disulfiram rxn with alcohol' },
        { name: 'Acarbose — GLUCOSE TABS ONLY', ts: '12:30', detail: 'Blocks sugar breakdown, only pure glucose works' },
        { name: 'SGLT-2 Inhibitors (-flozins)', ts: '14:00', detail: 'UTI/yeast, euglycemic DKA trap' },
        { name: 'GLP-1 Agonists (Semaglutide/Ozempic)', ts: '15:00', detail: 'BBW thyroid C-cell, CI in T1DM' },
        { name: 'DPP-4 Inhibitors (Sitagliptin)', ts: '15:45', detail: 'Weight neutral, pancreatitis' },
        { name: 'Meglitinides (Repaglinide)', ts: '16:15', detail: 'Skip meal = skip dose' },
        { name: 'Pramlintide — cut insulin by 50%', ts: '17:00', detail: 'Amylin mimetic, used WITH insulin' },
        { name: 'Exenatide (GLP-1, T2DM only)', ts: '17:00', detail: 'Weight loss, nausea, pancreatitis' },
        { name: 'DKA vs HHS (ketones = key)', ts: '18:15', detail: 'DKA = T1, HHS = T2, opposite glucose levels' },
        { name: 'K+ ≥ 3.3 before insulin', ts: '19:00', detail: 'FKI-D protocol, fatal arrhythmia risk' },
        { name: 'Glucagon — severe hypo rescue', ts: '19:45', detail: 'IM/SubQ/IV/intranasal, position on side' },
        { name: 'Sick Day Rule', ts: '20:45', detail: 'Never stop insulin in T1DM' },
      ],
      gaps: [],
      offbp: [],
      syllabus: [
        { topic: 'Insulins', items: [
          { name: 'Rapid Acting (Lispro)', detail: 'Onset, Peak, Duration, Purpose, Therapeutic Uses, Complications, Nursing Actions', coveredBy: 'Rapid-Acting Insulin (Lispro)' },
          { name: 'Short Acting (Regular)', detail: 'Know onset, peak, duration — ONLY insulin for IV use', coveredBy: 'Short-Acting (Regular) — ONLY IV insulin' },
          { name: 'Intermediate-Acting (NPH)', detail: 'Know onset, peak, duration — ONLY cloudy insulin', coveredBy: 'Intermediate (NPH) — ONLY cloudy' },
          { name: 'Long Acting (Glargine)', detail: 'No peak, basal insulin, never mix', coveredBy: 'Long-Acting (Glargine) — NEVER mix' },
          { name: 'Premixed 70/30 or 75/25', detail: '70% NPH + 30% Regular OR 75/25', coveredBy: 'Premixed 70/30 and 75/25' },
        ]},
        { topic: 'Oral Antidiabetics', items: [
          { name: 'Sulfonylureas', detail: 'Chlorpropamide, Glipizide, Tolazamide, Glyburide, Glimepiride', coveredBy: 'Sulfonylureas (all 5 named)' },
          { name: 'Biguanides (Metformin)', detail: '1st line T2DM, lactic acidosis, hold for contrast', coveredBy: 'Metformin — 1st line T2DM' },
          { name: 'Meglitinides (Repaglinide, Nateglinide)', detail: 'Non-sulfonylurea, skip meal = skip dose', coveredBy: 'Meglitinides (Repaglinide)' },
          { name: 'Alpha-glucosidase Inhibitors (Acarbose, Miglitol)', detail: 'Blocks sugar breakdown, glucose tabs only for hypo', coveredBy: 'Acarbose — GLUCOSE TABS ONLY' },
          { name: 'DPP-4 Inhibitors / Gliptins (Sitagliptin)', detail: 'Weight neutral, pancreatitis risk', coveredBy: 'DPP-4 Inhibitors (Sitagliptin)' },
          { name: 'SGLT-2 Inhibitors (Canagliflozin, Dapagliflozin, Empagliflozin)', detail: 'UTI/yeast infection risk, euglycemic DKA', coveredBy: 'SGLT-2 Inhibitors (-flozins)' },
          { name: 'GLP-1 (Semaglutide)', detail: 'Contraindicated for T1DM, BBW thyroid C-cell tumors', coveredBy: 'GLP-1 Agonists (Semaglutide/Ozempic)' },
        ]},
        { topic: 'Non-Insulin Injectable Antidiabetics', items: [
          { name: 'Amylin Mimetics (Pramlintide)', detail: 'Used WITH insulin, cut insulin dose 50%', coveredBy: 'Pramlintide — cut insulin by 50%' },
          { name: 'Incretin Mimetics (Exenatide)', detail: 'GLP-1, T2DM only, weight loss, pancreatitis', coveredBy: 'Exenatide (GLP-1, T2DM only)' },
        ]},
        { topic: 'Hyperglycemic Agent', items: [
          { name: 'Glucagon', detail: 'Severe hypo rescue, IM/SubQ/IV/intranasal', coveredBy: 'Glucagon — severe hypo rescue' },
          { name: 'Regular Insulin (for DKA/HHS)', detail: 'K+ ≥ 3.3 before giving, FKI-D protocol', coveredBy: 'K+ ≥ 3.3 before insulin' },
        ]},
      ]
    },
    {
      id: 'deck4',
      title: 'Thyroid, Pituitary & Adrenal Made Simple',
      label: 'Deck 4 — Endocrine Disorders',
      color: '#5F3DC4',
      status: 'uploaded',
      statusText: 'UPLOADED',
      youtubeId: '9nmNgaX8ndo',
      questionCount: '12-13',
      chapter: 'Chapters 42-44',
      subtitle: '32 slides • ~12-13 exam questions • Chapters 42-44',
      timestamps: [
        ['00:00','Intro — The Other Half of Endocrine'],
        ['00:30','Levothyroxine (Synthroid) — 4S Rule'],
        ['01:45','Methimazole (Tapazole) — Hyperthyroidism'],
        ['02:30','PTU — 1st Trimester + Thyroid Storm'],
        ['03:15','PTU vs Methimazole Comparison'],
        ['03:45','Agranulocytosis — Fever + Sore Throat = STOP'],
        ['04:15','Radioactive Iodine (I-131)'],
        ['05:00','Lugol\'s Solution — Use a Straw'],
        ['05:30','Thyroid Storm Protocol — Order Matters!'],
        ['06:15','QUIZ: 1st Trimester Graves\' Disease'],
        ['06:45','Somatropin — Growth Hormone'],
        ['07:15','Vasopressin — 3 Uses'],
        ['07:45','Desmopressin (DDAVP) — 4 Uses'],
        ['08:15','Octreotide — Gallstone Risk'],
        ['08:45','Pegvisomant Paradox — IGF-1 not GH'],
        ['09:30','Lanreotide — Same Family'],
        ['09:45','QUIZ: Pegvisomant + Elevated GH'],
        ['10:15','Addison\'s vs Cushing\'s'],
        ['10:45','Hydrocortisone — Never Stop Abruptly'],
        ['11:15','Steroid Potency Ladder'],
        ['11:45','Dexamethasone — 3 Uses, 25x Potent'],
        ['12:15','Fludrocortisone — Mineralocorticoid Only'],
        ['12:45','Sodium Thiosulfate — 3 Antidote Uses'],
        ['13:15','QUIZ: Stop Steroids Abruptly?'],
      ],
      said: [
        { name: 'Levothyroxine (Synthroid) + 4S Rule', ts: '00:30', detail: 'Empty stomach, separate Ca/Fe 4h, TSH monitoring' },
        { name: 'Methimazole (Tapazole)', ts: '01:45', detail: 'Preferred antithyroid, NOT 1st trimester' },
        { name: 'PTU — 1st Trimester + Thyroid Storm', ts: '02:30', detail: 'BBW hepatotoxicity, blocks T4→T3' },
        { name: 'Agranulocytosis = STOP drug', ts: '03:45', detail: 'Fever + sore throat, check CBC' },
        { name: 'Radioactive Iodine (I-131)', ts: '04:15', detail: 'Absolute CI pregnancy, radiation isolation 5-7 days' },
        { name: 'Lugol\'s Solution + Iodism', ts: '05:00', detail: 'Use straw, metallic taste, parotid swelling' },
        { name: 'Thyroid Storm Protocol (order matters)', ts: '05:30', detail: 'PTU → Iodine → BB → Dex → supportive, no aspirin' },
        { name: 'Sodium Thiosulfate — 3 antidote uses', ts: '12:45', detail: 'Cyanide, iodism, cisplatin nephrotoxicity' },
        { name: 'Somatropin (Growth Hormone)', ts: '06:45', detail: 'SubQ daily, IGF-1 monitoring, CI active malignancy' },
        { name: 'Vasopressin (ADH) — 3 uses', ts: '07:15', detail: 'DI, septic shock, varices, water intoxication risk' },
        { name: 'Desmopressin (DDAVP) — 4 uses', ts: '07:45', detail: 'DI, enuresis, hemophilia A, vWD type 1' },
        { name: 'Octreotide (Sandostatin)', ts: '08:15', detail: 'Acromegaly, carcinoid, gallstones, baseline US' },
        { name: 'Pegvisomant Paradox', ts: '08:45', detail: 'GH goes UP (expected), monitor IGF-1 not GH' },
        { name: 'Lanreotide (Somatuline)', ts: '09:30', detail: 'Same class as octreotide, monthly SubQ' },
        { name: 'Addison\'s vs Cushing\'s', ts: '10:15', detail: 'Opposite electrolytes, opposite everything' },
        { name: 'Hydrocortisone + NEVER stop abruptly', ts: '10:45', detail: 'Addisonian crisis, stress dosing during illness' },
        { name: 'Steroid Potency Ladder', ts: '11:15', detail: '1x → 4x → 5x → 25x' },
        { name: 'Dexamethasone — 25x, 3 uses', ts: '11:45', detail: 'Cushing dx, fetal lungs, cerebral edema' },
        { name: 'Fludrocortisone (Florinef)', ts: '12:15', detail: 'Mineralocorticoid only, Na+/K+ balance, Addison\'s' },
      ],
      gaps: [],
      offbp: [],
      syllabus: [
        { topic: 'Endocrine Disorders — Thyroid', items: [
          { name: 'Levothyroxine', detail: 'Hypothyroidism, empty stomach, separate Ca/Fe', coveredBy: 'Levothyroxine (Synthroid) + 4S Rule' },
          { name: 'Methimazole', detail: 'Preferred antithyroid, NOT 1st trimester', coveredBy: 'Methimazole (Tapazole)' },
          { name: 'PTU (Propylthiouracil)', detail: '1st trimester + thyroid storm, BBW hepatotoxicity', coveredBy: 'PTU — 1st Trimester + Thyroid Storm' },
          { name: 'Radioactive Iodine (I-131)', detail: 'Ablation therapy, CI pregnancy', coveredBy: 'Radioactive Iodine (I-131)' },
          { name: 'Lugol\'s Solution', detail: 'Pre-surgery thyroid, use straw', coveredBy: 'Lugol\'s Solution + Iodism' },
          { name: 'Iodism', detail: 'Metallic taste, parotid swelling — toxicity sign', coveredBy: 'Lugol\'s Solution + Iodism' },
          { name: 'Sodium Thiosulfate', detail: 'Antidote: cyanide, iodism, cisplatin', coveredBy: 'Sodium Thiosulfate — 3 antidote uses' },
        ]},
        { topic: 'Growth Hormones & Pituitary', items: [
          { name: 'Somatropin', detail: 'Growth hormone, SubQ daily, IGF-1 monitoring', coveredBy: 'Somatropin (Growth Hormone)' },
          { name: 'Vasopressin', detail: 'ADH — DI, septic shock, varices', coveredBy: 'Vasopressin (ADH) — 3 uses' },
          { name: 'Desmopressin', detail: 'DI, enuresis, hemophilia A, vWD type 1', coveredBy: 'Desmopressin (DDAVP) — 4 uses' },
        ]},
        { topic: 'Hyperpituitarism Medications', items: [
          { name: 'Octreotide', detail: 'Acromegaly, carcinoid, gallstone risk', coveredBy: 'Octreotide (Sandostatin)' },
          { name: 'Lanreotide', detail: 'Same class as octreotide, monthly SubQ', coveredBy: 'Lanreotide (Somatuline)' },
          { name: 'Pegvisomant', detail: 'GH receptor antagonist, monitor IGF-1 not GH', coveredBy: 'Pegvisomant Paradox' },
        ]},
        { topic: 'Adrenal Hormone Replacement', items: [
          { name: 'Hydrocortisone', detail: 'Addison\'s, never stop abruptly, stress dosing', coveredBy: 'Hydrocortisone + NEVER stop abruptly' },
          { name: 'Glucocorticoids', detail: 'Steroid potency ladder: 1x→4x→5x→25x', coveredBy: 'Steroid Potency Ladder' },
          { name: 'Dexamethasone', detail: '25x potent — Cushing dx, fetal lungs, cerebral edema', coveredBy: 'Dexamethasone — 25x, 3 uses' },
          { name: 'Fludrocortisone', detail: 'Mineralocorticoid only, Na+/K+ balance, Addison\'s', coveredBy: 'Fludrocortisone (Florinef)' },
        ]},
      ]
    },
    {
      id: 'deck2',
      title: 'Infectious Disease & Antimicrobials',
      label: 'Deck 2 — Antimicrobials',
      color: '#0B7285',
      status: 'uploaded',
      statusText: 'UPLOADED',
      youtubeId: 'VluJCc8MNlI',
      notRecorded: false,
      questionCount: '18-22',
      chapter: 'Chapters 39-40',
      subtitle: '~48 slides (blueprint-aligned) • ~18-22 exam questions • LARGEST section',
      timestamps: [
        ['00:00','Intro — Why This Section = 18-22 Exam Questions'],
        ['00:45','Antimicrobial Cheat Sheet Overview'],
        ['01:15','Bactericidal vs Bacteriostatic'],
        ['02:00','Culture and Sensitivity + Superinfection'],
        ['02:45','Beta-Lactams — Cell Wall Killers'],
        ['03:30','Amoxicillin — MONO Rash Trap'],
        ['04:15','Cephalosporin Generations'],
        ['05:00','PCN Allergy Cross-Reactivity — Aztreonam'],
        ['05:45','QUIZ: PCN Anaphylaxis'],
        ['06:15','Vancomycin — MRSA, Trough 10-20'],
        ['07:00','Red Man Syndrome — NOT an Allergy'],
        ['07:45','Aminoglycosides — Nephro vs Ototoxicity'],
        ['09:00','Doxycycline — PCD Mnemonic'],
        ['09:45','30S vs 50S Ribosomal Targets'],
        ['10:45','TMP-SMX (Bactrim)'],
        ['12:00','Fluoroquinolones — 4 Black Box Warnings'],
        ['12:45','Metronidazole (Flagyl) — No Alcohol'],
        ['14:00','TB RIPE Regimen'],
        ['14:45','RIPE Side Effects Mnemonic'],
        ['16:00','Amphotericin B — DHAM Pre-Meds'],
        ['17:00','Acyclovir — HSV/VZV'],
        ['18:00','Oseltamivir (Tamiflu) — 48 Hour Window'],
        ['18:30','HIV / HAART'],
        ['20:00','Urinary Anti-Infectives'],
        ['20:45','Antibiotic Prophylaxis'],
        ['22:15','Rapid Fire Review — 15 Facts'],
      ],
      said: [
        { name: 'Amoxicillin (Penicillin)', ts: '03:30', detail: 'MOA: cell wall synthesis inhibitor. Mono rash trap — NOT a true allergy' },
        { name: 'Cephalosporins (Cefazolin/Ceftriaxone)', ts: '04:15', detail: '4 generations. ~1% cross-reactivity with PCN allergy' },
        { name: 'Vancomycin', ts: '06:15', detail: 'MRSA drug. Trough 10-20. Red Man Syndrome = infuse slowly, NOT an allergy' },
        { name: 'Aztreonam', ts: '05:00', detail: 'Safe in true PCN allergy — no cross-reactivity' },
        { name: 'Gentamicin (Aminoglycoside)', ts: '07:45', detail: 'Nephrotoxicity (reversible) + Ototoxicity (IRREVERSIBLE). Peak & trough' },
        { name: 'Doxycycline (Tetracycline)', ts: '09:00', detail: 'PCD mnemonic: Photosensitivity, no Children <8, no Dairy/antacids' },
        { name: 'TMP-SMX (Bactrim)', ts: '10:45', detail: 'Sulfonamide — SCAK: Sulfa allergy, Crystalluria (hydrate), Agranulocytosis, Kernicterus' },
        { name: 'Fluoroquinolones (Ciprofloxacin)', ts: '12:00', detail: '4 BBWs: tendon rupture, peripheral neuropathy, CNS effects, aortic dissection. 2-6 rule' },
        { name: 'Metronidazole (Flagyl)', ts: '12:45', detail: 'Disulfiram reaction — NO alcohol. C. diff first-line' },
        { name: 'Isoniazid (INH) — TB', ts: '14:00', detail: 'RIPE regimen. ALWAYS give with B6 (pyridoxine). Hepatotoxicity — monitor LFTs' },
        { name: 'Amphotericin B (Antifungal)', ts: '16:00', detail: 'DHAM pre-meds (Diphenhydramine, Hydrocortisone, Acetaminophen, Meperidine). Nephrotoxic' },
        { name: 'Acyclovir (Antiviral)', ts: '17:00', detail: 'HSV/VZV. Hydration critical — crystalluria risk. Renal dosing' },
        { name: 'Ganciclovir (Antiviral)', ts: '17:00', detail: 'CMV treatment. Chemo precautions — bone marrow suppression' },
        { name: 'Oseltamivir (Tamiflu)', ts: '18:00', detail: '48-hour window — must start within 48h of symptom onset' },
        { name: 'HIV / HAART', ts: '18:30', detail: 'AZT (zidovudine) in pregnancy. >95% adherence required. CD4/viral load monitoring' },
        // Below: not in video but have practice questions
        { name: 'Carbapenems (Imipenem/Meropenem)', detail: 'Broadest spectrum beta-lactam. Imipenem + cilastatin. Seizure risk.', notInVideo: true },
        { name: 'Macrolides (Azithromycin)', detail: '50S ribosomal inhibitor. QT prolongation. Z-pack.', notInVideo: true },
        { name: 'Rifampin (TB)', detail: 'RIPE drug. Red/orange body fluids. CYP450 inducer — reduces OCP, warfarin.', notInVideo: true },
        { name: 'Pyrazinamide (TB)', detail: 'RIPE drug. Hepatotoxicity. Increases uric acid → gout.', notInVideo: true },
        { name: 'Ethambutol (TB)', detail: 'RIPE drug. Optic neuritis — test visual acuity BEFORE starting.', notInVideo: true },
        { name: 'Ketoconazole (Antifungal)', detail: 'BBW hepatotoxicity. CYP3A4 inhibitor. Needs acidic pH for absorption.', notInVideo: true },
        { name: 'Ofloxacin (Fluoroquinolone)', detail: 'Same class as Cipro/Levo. Same 4 BBWs. Ophthalmic/otic drops available.', notInVideo: true },
        { name: 'Fosfomycin', detail: 'Single 3g dose for uncomplicated UTI. Safe in pregnancy.', notInVideo: true },
        { name: 'Methenamine', detail: 'UTI prophylaxis ONLY. Needs acidic urine pH <5.5. Give with vitamin C.', notInVideo: true },
        { name: 'Nitrofurantoin (Macrobid)', detail: 'UTI drug. Brown urine. CI if CrCl <30. Take with food.', notInVideo: true },
        { name: 'Phenazopyridine (Pyridium)', detail: 'Urinary analgesic ONLY — not an antibiotic. Orange urine. Max 2 days.', notInVideo: true },
        { name: 'Antibiotic Prophylaxis', detail: 'Surgical: cefazolin. Cardiac/IE: amoxicillin. UTI: TMP-SMX. STD: ceftriaxone + azithromycin.', notInVideo: true },
      ],
      slidesHave: [],
      syllabus: [
        { topic: 'Beta-Lactam Antibiotics (Cell Wall Inhibitors)', items: [
          { name: 'Penicillins (Amoxicillin)', detail: 'MOA, allergy assessment, anaphylaxis, mono rash trap', coveredBy: 'Amoxicillin (Penicillin)' },
          { name: 'Cephalosporins (4 generations)', detail: 'Cefazolin (1st), Ceftriaxone (3rd), cross-reactivity', coveredBy: 'Cephalosporins (Cefazolin/Ceftriaxone)' },
          { name: 'Carbapenems (Imipenem, Meropenem)', detail: 'Broadest spectrum, seizure risk, cilastatin', coveredBy: 'Carbapenems (Imipenem/Meropenem)' },
          { name: 'Monobactam (Aztreonam)', detail: 'Safe with PCN allergy — no cross-reactivity', coveredBy: 'Aztreonam' },
          { name: 'Vancomycin', detail: 'MRSA, Red Man Syndrome, trough levels 10-20', coveredBy: 'Vancomycin' },
        ]},
        { topic: 'Protein Synthesis Inhibitors (Ribosomal)', items: [
          { name: 'Aminoglycosides (Gentamicin)', detail: 'Nephrotoxicity + ototoxicity, peak & trough levels', coveredBy: 'Gentamicin (Aminoglycoside)' },
          { name: 'Tetracyclines (Doxycycline)', detail: 'Photosensitivity, no children <8, no dairy', coveredBy: 'Doxycycline (Tetracycline)' },
          { name: 'Macrolides (Azithromycin)', detail: 'QT prolongation, GI upset, Z-pack', coveredBy: 'Macrolides (Azithromycin)' },
        ]},
        { topic: 'DNA/Metabolic Inhibitors', items: [
          { name: 'TMP-SMX (Bactrim)', detail: 'Sulfonamide, crystalluria, agranulocytosis, kernicterus', coveredBy: 'TMP-SMX (Bactrim)' },
          { name: 'Fluoroquinolones (Cipro, Levo, Ofloxacin)', detail: '4 Black Box Warnings, tendon rupture, 2-6 rule', coveredBy: 'Fluoroquinolones (Ciprofloxacin)' },
          { name: 'Ofloxacin', detail: 'Same class as Cipro/Levo. Ophthalmic/otic drops', coveredBy: 'Ofloxacin (Fluoroquinolone)' },
          { name: 'Metronidazole (Flagyl)', detail: 'C. diff first-line, disulfiram reaction with alcohol', coveredBy: 'Metronidazole (Flagyl)' },
        ]},
        { topic: 'TB Treatment (RIPE Regimen)', items: [
          { name: 'Isoniazid (INH)', detail: 'Give with B6, hepatotoxicity, peripheral neuropathy', coveredBy: 'Isoniazid (INH) — TB' },
          { name: 'Rifampin', detail: 'Red/orange body fluids, CYP450 inducer, reduces OCP', coveredBy: 'Rifampin (TB)' },
          { name: 'Pyrazinamide', detail: 'Gout/joint pain, hepatotoxicity, intensive phase', coveredBy: 'Pyrazinamide (TB)' },
          { name: 'Ethambutol', detail: 'Optic neuritis — visual acuity testing before and during', coveredBy: 'Ethambutol (TB)' },
        ]},
        { topic: 'Antifungals', items: [
          { name: 'Amphotericin B', detail: 'DHAM pre-meds, nephrotoxicity, infusion reactions', coveredBy: 'Amphotericin B (Antifungal)' },
          { name: 'Ketoconazole', detail: 'BBW hepatotoxicity, CYP3A4 inhibitor, needs acidic pH', coveredBy: 'Ketoconazole (Antifungal)' },
        ]},
        { topic: 'Antivirals', items: [
          { name: 'Acyclovir (HSV/VZV)', detail: 'Hydration, crystalluria, renal dosing', coveredBy: 'Acyclovir (Antiviral)' },
          { name: 'Ganciclovir (CMV)', detail: 'Bone marrow suppression, chemo precautions', coveredBy: 'Ganciclovir (Antiviral)' },
          { name: 'Oseltamivir (Tamiflu)', detail: '48-hour window for flu treatment', coveredBy: 'Oseltamivir (Tamiflu)' },
        ]},
        { topic: 'HIV / Antiretrovirals', items: [
          { name: 'HAART / Combination Therapy', detail: '>95% adherence, CD4/viral load, AZT in pregnancy', coveredBy: 'HIV / HAART' },
        ]},
        { topic: 'Urinary Anti-Infectives', items: [
          { name: 'Fosfomycin', detail: 'Single 3g dose UTI, safe in pregnancy', coveredBy: 'Fosfomycin' },
          { name: 'Methenamine', detail: 'UTI prophylaxis only, needs acidic urine pH <5.5', coveredBy: 'Methenamine' },
          { name: 'Nitrofurantoin (Macrobid)', detail: 'UTI treatment/prophylaxis, brown urine, CI if CrCl <30', coveredBy: 'Nitrofurantoin (Macrobid)' },
          { name: 'Phenazopyridine (Pyridium)', detail: 'Urinary analgesic ONLY (not antibiotic), orange urine, max 2 days', coveredBy: 'Phenazopyridine (Pyridium)' },
        ]},
        { topic: 'Antibiotic Prophylaxis', items: [
          { name: 'Surgical, Cardiac/IE, UTI, STD protocols', detail: 'Cefazolin, amoxicillin, TMP-SMX, ceftriaxone + azithromycin', coveredBy: 'Antibiotic Prophylaxis' },
        ]},
      ],
      gaps: [],
      offbp: [
        { name: 'NSAIDs / COX-1 vs COX-2', detail: 'Ch 29, NOT on Exam 2' },
        { name: 'Ketorolac (Toradol)', detail: 'Ch 29, NOT on Exam 2' },
        { name: 'Aspirin vs Acetaminophen', detail: 'Ch 29, NOT on Exam 2' },
        { name: 'Antigout (Colchicine, Allopurinol)', detail: 'Ch 29, NOT on Exam 2' },
        { name: 'Oseltamivir (Tamiflu)', detail: 'Not in blueprint antiviral list' },
        { name: 'Linezolid vs Clindamycin', detail: 'Not named on blueprint' },
      ]
    },
    {
      id: 'deck1',
      title: 'Allergy, Immunology & Hematology',
      label: 'Deck 1 — Blood & Immunity',
      color: '#C92A2A',
      status: 'not-recorded',
      statusText: 'SLIDES READY — VIDEO COMING SOON',
      youtubeId: null,
      questionCount: '4-6',
      chapter: 'ATI Modules + Ch 9, 11, 32',
      subtitle: '32 slides (blueprint-aligned) • ~4-6 exam questions • Script ready',
      timestamps: [],
      said: [],
      gaps: [
        { name: 'Hemolytic anemia', detail: 'Blueprint item — no content exists' },
        { name: 'Blood Transfusion / Blood Products', detail: 'Transfusion reactions, monitoring' },
        { name: 'Immunosuppressants', detail: 'Blueprint item' },
        { name: 'Childhood immunizations', detail: 'Blueprint item' },
        { name: 'Hepatitis B vaccine', detail: 'Blueprint item' },
        { name: 'DTP vaccine', detail: 'Blueprint item' },
        { name: 'Flu vaccine', detail: 'Blueprint item' },
        { name: 'Zoster vaccine', detail: 'Blueprint item' },
        { name: 'COVID-19 vaccine', detail: 'Blueprint item' },
        { name: 'Heparin', detail: 'Anticoagulant — blueprint item' },
        { name: 'LMWH (Enoxaparin)', detail: 'Anticoagulant' },
        { name: 'Warfarin (Coumadin)', detail: 'Vitamin K inhibitor, INR 2-3' },
        { name: 'Direct Thrombin Inhibitors', detail: 'Anticoagulant' },
        { name: 'Direct Factor Xa Inhibitors', detail: 'Anticoagulant' },
        { name: 'Antiplatelets', detail: 'Blueprint item' },
        { name: 'Thrombolytics', detail: 'Blueprint item' },
        { name: 'Erythropoietic (Epoetin alfa)', detail: 'Growth factor' },
        { name: 'Leucopoietic (Filgrastim)', detail: 'Growth factor' },
        { name: 'Thrombopoietic (Oprelvekin)', detail: 'Growth factor' },
        { name: 'GM-CSF (Sargramostim)', detail: 'Growth factor' },
      ],
      offbp: []
    },
  ]
};
