// ══════════════════════════════════════════════
// ADULT HEALTH DATA — study topics by body system
// Structure matches STUDY_DATA for tracker.js compatibility
// ══════════════════════════════════════════════

window.STUDY_DATA_AH = {
  siteName: 'Study with Tiago',
  course: 'Adult Health Nursing',

  videos: [
    // ── Hematology ──
    {
      id: 'ah_heme',
      title: 'Hematology & Blood Disorders',
      label: 'Hematology',
      color: '#C92A2A',
      status: 'uploaded',
      statusText: 'VIDEO AVAILABLE',
      youtubeId: '7Ctl6uAWgms',
      questionCount: '~27',
      chapter: 'Ch 23-25',
      subtitle: 'RBC, WBC, Lymphoma, Hemostasis',
      notRecorded: false,
      slidesHave: [
        { name: 'Erythropoiesis & RBC Development' },
        { name: 'Hemoglobin Structure' },
        { name: 'Iron Deficiency Anemia' },
        { name: 'B12 Deficiency / Pernicious Anemia' },
        { name: 'Folate Deficiency' },
        { name: 'Sickle Cell Disease' },
        { name: 'Thalassemia' },
        { name: 'G6PD Deficiency' },
        { name: 'Polycythemia (3 Types)' },
        { name: 'Blood Typing (ABO & Rh)' },
        { name: 'Transfusion Components' },
        { name: 'Transfusion Reactions' },
        { name: 'WBC Basics' },
        { name: 'Neutropenia / Leukopenia' },
        { name: 'Hodgkin Disease' },
        { name: 'Non-Hodgkin Lymphoma (NHL)' },
        { name: 'Leukemia' },
        { name: 'Multiple Myeloma' },
        { name: 'Tumor Lysis Syndrome (TLS)' },
        { name: 'DIC (Disseminated Intravascular Coagulation)' },
        { name: 'ITP (Immune Thrombocytopenic Purpura)' },
        { name: 'Hemophilia A & B' },
        { name: 'von Willebrand Disease' },
        { name: 'Heparin & Warfarin' },
        { name: 'DOACs' },
        { name: 'HIT (Heparin-Induced Thrombocytopenia)' },
        { name: 'Antiplatelets' },
        { name: 'Thrombolytics (Alteplase)' },
        { name: 'Growth Factors' },
      ],
      gaps: [],
    },

    // ── Diabetes ──
    {
      id: 'ah_diabetes',
      title: 'Diabetes & Emergencies',
      label: 'Diabetes',
      color: '#2B8A3E',
      status: 'uploaded',
      statusText: 'VIDEO AVAILABLE',
      youtubeId: 'Ge5nu_SuNp4',
      questionCount: '~24',
      chapter: 'Ch 41',
      subtitle: 'Insulins, Oral Agents, DKA/HHS',
      notRecorded: false,
      slidesHave: [
        { name: 'Type 1 vs Type 2 Diabetes' },
        { name: 'Rapid-Acting Insulin (Lispro, Aspart)' },
        { name: 'Short-Acting (Regular)' },
        { name: 'Intermediate (NPH)' },
        { name: 'Long-Acting (Glargine/Lantus)' },
        { name: 'Insulin Administration' },
        { name: 'Metformin Safety' },
        { name: 'Sulfonylureas (Glipizide, Glyburide)' },
        { name: 'SGLT-2 Inhibitors' },
        { name: 'GLP-1 Agonists (Semaglutide/Ozempic)' },
        { name: 'DPP-4 Inhibitors (Sitagliptin)' },
        { name: 'DKA vs HHS' },
        { name: 'DKA Fluid Management' },
        { name: 'Hypoglycemia Management' },
        { name: 'Dawn vs Somogyi Phenomenon' },
        { name: 'Hypoglycemia Unawareness' },
        { name: 'Sick Day Rules' },
        { name: 'A1C and Diagnostic Criteria' },
        { name: 'Diabetic Foot Care' },
        { name: 'Chronic Complications' },
      ],
      gaps: [],
    },

    // ── Endocrine ──
    {
      id: 'ah_endo',
      title: 'Thyroid, Pituitary & Adrenal',
      label: 'Endocrine',
      color: '#5F3DC4',
      status: 'uploaded',
      statusText: 'VIDEO AVAILABLE',
      youtubeId: 'MrFMIWnel2M',
      questionCount: '~24',
      chapter: 'Ch 42-44',
      subtitle: 'Hormonal Disorders & Emergencies',
      notRecorded: false,
      slidesHave: [
        { name: 'Hypothyroidism / Levothyroxine' },
        { name: 'Hyperthyroidism / Graves\' Disease' },
        { name: 'Methimazole (Tapazole)' },
        { name: 'PTU (Propylthiouracil)' },
        { name: 'Agranulocytosis' },
        { name: 'Thyroid Storm Protocol' },
        { name: 'Myxedema Coma' },
        { name: 'Post-Thyroidectomy Care' },
        { name: 'Diabetes Insipidus (DI)' },
        { name: 'SIADH vs Diabetes Insipidus' },
        { name: 'Desmopressin (DDAVP)' },
        { name: 'Acromegaly' },
        { name: 'Post-Hypophysectomy Care' },
        { name: 'Addison\'s Disease' },
        { name: 'Cushing\'s Syndrome' },
        { name: 'Addisonian Crisis' },
        { name: 'Hydrocortisone' },
        { name: 'Steroid Side Effects' },
        { name: 'Hyperparathyroidism' },
        { name: 'Pheochromocytoma' },
      ],
      gaps: [],
    },

    // ── Renal ──
    {
      id: 'ah_renal',
      title: 'Renal & Urologic Disorders',
      label: 'Renal',
      color: '#1864AB',
      status: 'uploaded',
      statusText: 'VIDEO AVAILABLE',
      youtubeId: 'VA8fOrMcHNA',
      questionCount: '~21',
      chapter: 'Ch 37',
      subtitle: 'AKI, CKD, Dialysis, Urologic',
      notRecorded: false,
      slidesHave: [
        { name: 'Acute Kidney Injury — Classification' },
        { name: 'Pre-renal AKI' },
        { name: 'Intrarenal AKI' },
        { name: 'Post-renal AKI' },
        { name: 'AKI Phases (Oliguric, Diuretic, Recovery)' },
        { name: 'Chronic Kidney Disease' },
        { name: 'Uremic Syndrome' },
        { name: 'CKD Electrolytes' },
        { name: 'CKD Diet' },
        { name: 'Hemodialysis — AV Fistula' },
        { name: 'Peritoneal Dialysis' },
        { name: 'Hemodialysis Complications' },
        { name: 'Kidney Stones (Urolithiasis)' },
        { name: 'Pyelonephritis' },
        { name: 'UTI & CAUTI Prevention' },
        { name: 'Autonomic Dysreflexia' },
        { name: 'CKD Medications to Avoid' },
        { name: 'Renal Osteodystrophy' },
      ],
      gaps: [],
    },
  ],
};

console.log('STUDY_DATA_AH loaded:', STUDY_DATA_AH.videos.length, 'topics');
