// ══════════════════════════════════════════════
// Flashcard Data — 60 cards for Adult Health Exam 3
// Source: ATI Gold Standard Complete Review (1,034 lines)
// Sections: Diabetes, Thyroid, Pituitary/Adrenal, Renal, Hematology, Quick Ref
// ══════════════════════════════════════════════

window.FLASHCARD_DATA_AH = {
  sections: [
    { id: 'diabetes', label: 'Diabetes', icon: '🩺', color: '#2B8A3E' },
    { id: 'thyroid', label: 'Thyroid', icon: '🦋', color: '#5F3DC4' },
    { id: 'pitadrenal', label: 'Pituitary / Adrenal', icon: '🧠', color: '#E67700' },
    { id: 'renal', label: 'Renal', icon: '🫘', color: '#1971C2' },
    { id: 'hematology', label: 'Hematology', icon: '🩸', color: '#C92A2A' },
    { id: 'quickref', label: 'Quick Reference', icon: '📋', color: '#495057' },
  ],
  cards: [
    // ═══ DIABETES (16 cards) ═══
    { section: 'diabetes', drugName: 'Type 1 vs Type 2 Diabetes', brandName: '', drugClass: 'Disease Comparison', purpose: 'Know the key differences — onset, body type, treatment', facts: ['Type 1: autoimmune beta cell destruction, sudden onset, thin/normal, ALWAYS needs insulin, ketosis-prone', 'Type 2: insulin resistance + decreased production, gradual onset, often obese, diet → oral meds → maybe insulin', 'The 3 Ps: Polyuria, Polydipsia, Polyphagia', 'LADA = Type 1 variant in adults — looks like T2 at first but is autoimmune', 'Gestational DM: screen 24-28 weeks, resolves ~6 weeks postpartum'], mnemonic: 'Type 1 = NO insulin. Type 2 = NOT ENOUGH insulin.', icon: '⚖️' },

    { section: 'diabetes', drugName: 'Insulin Types', brandName: 'Rapid → Short → Intermediate → Long', drugClass: 'Insulin Classification', purpose: 'Know onset, peak, duration of each type', facts: ['Rapid (Lispro/Aspart): 10-30 min onset, 1-3 hr peak, 3-5 hr duration — give BEFORE meals', 'Short (Regular): 30-60 min onset, 2-4 hr peak — ONLY insulin for IV', 'Intermediate (NPH): 1-2 hr onset, 6-14 hr peak — ONLY cloudy insulin, ONLY one you can mix', 'Long (Glargine/Detemir): 1-2 hr onset, NO peak, 24 hr — NEVER mix, same time daily', 'Inhaled insulin: contraindicated in COPD/asthma (bronchospasm)'], mnemonic: 'Rapid = Race, Regular = Reliable for IV, NPH = Not Perfectly Honest about peak', icon: '💉' },

    { section: 'diabetes', drugName: 'Insulin Mixing Rules', brandName: 'RN = Regular before NPH', drugClass: 'Critical Nursing Concept', purpose: 'Clear before Cloudy — prevent contamination', facts: ['Draw Regular (CLEAR) FIRST, then NPH (CLOUDY)', 'Roll NPH gently — NEVER shake', 'NEVER mix Glargine or Detemir with anything', 'Premixed 70/30 = 70% NPH + 30% Regular', 'Peak times = highest hypoglycemia risk — check the table'], mnemonic: 'RN = Regular Nurse draws Regular first!', icon: '🩺' },

    { section: 'diabetes', drugName: 'Metformin', brandName: 'Glucophage', drugClass: 'Biguanide', purpose: 'First-line for Type 2 DM', facts: ['Lactic acidosis = life-threatening SE — monitor for S/S', 'HOLD 24-48hr before/after IV contrast dye', 'GI upset — take WITH food', 'Does NOT cause hypoglycemia alone', 'No alcohol (increases lactic acidosis risk)', 'B12/folate supplement recommended'], mnemonic: 'METformin MET its match with contrast — hold 48hr!', icon: '🥇' },

    { section: 'diabetes', drugName: 'Sulfonylureas', brandName: 'Glipizide / Glyburide / Amaryl', drugClass: 'Sulfonylureas', purpose: 'Stimulates pancreas to release MORE insulin', facts: ['HYPOGLYCEMIA = #1 concern', 'Weight gain common', 'Disulfiram-like reaction with alcohol', 'CI in sulfa allergy', 'Take 30 min before meals', 'Beta-blockers MASK tachycardia (hypo warning sign)'], mnemonic: 'GLI- prefix = GLucose goes Low = hypoglycemia', icon: '⚠️' },

    { section: 'diabetes', drugName: 'Meglitinides & TZDs', brandName: 'Repaglinide / Pioglitazone', drugClass: 'Oral Antidiabetics', purpose: 'Short-acting secretagogue + insulin sensitizer', facts: ['Repaglinide: "Skip the meal, skip the dose" — rapid onset, short duration', 'TZDs (Pioglitazone): increases insulin sensitivity', 'TZD BLACK BOX: MI and heart failure risk', 'TZD: fluid retention, hepatotoxicity — check LFTs', 'TZD: reduces oral contraceptive effectiveness', 'TZD: contraindicated in heart failure'], mnemonic: 'Repag = PAY only when you eat | TZD = Think Zonking Da heart', icon: '🍽️' },

    { section: 'diabetes', drugName: 'Alpha-Glucosidase Inhibitors', brandName: 'Acarbose / Miglitol', drugClass: 'Carb Blockers', purpose: 'Delays carbohydrate digestion', facts: ['Take with FIRST BITE of each meal', 'If hypoglycemic: ONLY glucose tablets/gel work!', 'Regular sugar/juice will NOT work (drug blocks digestion)', 'GI: gas, bloating, diarrhea (common)', 'Does NOT cause hypoglycemia alone'], mnemonic: 'ACARbose = A CARB blocker — glucose tabs ONLY for hypo', icon: '🍞' },

    { section: 'diabetes', drugName: 'DPP-4 & SGLT2 Inhibitors', brandName: 'Sitagliptin / Canagliflozin', drugClass: 'Newer Oral Agents', purpose: 'DPP-4 boosts incretins, SGLT2 blocks kidney glucose reabsorption', facts: ['DPP-4 (Sitagliptin): pancreatitis risk, weight neutral, low hypo risk', 'SGLT2 (-gliflozin): UTIs and yeast infections', 'SGLT2: euglycemic DKA (DKA with NORMAL glucose!)', 'SGLT2: weight loss + CV benefits', 'SGLT2: lower leg amputations (canagliflozin)', 'SGLT2: also used for heart failure'], mnemonic: 'DPP-4 = Don\'t Provoke Pancreas | SGLT2 = Sugar Goes to Loo, Twice', icon: '🚽' },

    { section: 'diabetes', drugName: 'GLP-1 Agonists', brandName: 'Exenatide / Liraglutide', drugClass: 'Incretin Mimetics', purpose: 'SubQ injection — mimics GLP-1 hormone', facts: ['SubQ 60 min BEFORE meals — never AFTER', 'Oral meds: 1 hr before or 2 hr after injection', 'Pancreatitis risk (severe abd pain → stop)', 'Weight loss (appetite suppression)', 'BBW: Thyroid C-cell tumors', 'CI in Type 1 DM and MTC/MEN2'], mnemonic: 'GLP-1 = Great for Losing Pounds but check Thyroid', icon: '🏋️' },

    { section: 'diabetes', drugName: 'Pramlintide', brandName: 'Symlin', drugClass: 'Amylin Analog', purpose: 'Used WITH insulin — slows gastric emptying', facts: ['Cut premeal rapid/short insulin by 50%', 'Inject at least 2 inches from insulin site', 'Slows gastric emptying, reduces glucagon', 'Used in BOTH Type 1 and Type 2', 'Nausea is most common SE'], mnemonic: 'PRAMlintide = PRAMbulance — slow down, cut insulin in half', icon: '🚑' },

    { section: 'diabetes', drugName: 'Hypoglycemia', brandName: 'BG < 70 mg/dL', drugClass: 'Diabetic Emergency', purpose: 'Rule of 15 — act fast, prevent brain damage', facts: ['Signs: cool/clammy, shaky, sweaty, tachy, confused', 'Skin: Hypo = cool, clammy | Hyper = warm, dry', 'Rule of 15: 15g fast carb → wait 15 min → recheck', 'After 3 failed attempts → call MD', 'Unconscious: lateral position → Glucagon 1mg IM or D50 IV', 'Teach family to inject glucagon', 'Avoid fats (ice cream) — slow absorption'], mnemonic: '15 grams, 15 minutes, lateral if unconscious', icon: '🚨' },

    { section: 'diabetes', drugName: 'DKA vs HHS', brandName: '', drugClass: 'Hyperglycemic Emergencies', purpose: 'Both = crisis. Know the differences.', facts: ['DKA: Type 1, glucose 300-800, ketones PRESENT, pH < 7.35, Kussmaul breathing, fruity breath', 'HHS: Type 2 (older adults), glucose > 600-1200+, NO ketones, seizures, higher mortality (20%)', '#1 DKA trigger = INFECTION', 'Both: Check K+ ≥ 3.3 BEFORE giving insulin', 'HHS unique: reversible paralysis, altered mental status'], mnemonic: 'DKA = Deadly Ketone Attack | HHS = Horribly High Sugar', icon: '🔥' },

    { section: 'diabetes', drugName: 'DKA Treatment Protocol', brandName: 'Fluids → K+ Check → Insulin', drugClass: 'Emergency Treatment', purpose: 'The ORDER matters — fluids first, check K+, then insulin', facts: ['Step 1: 0.9% NS first → 0.45% NS → D5W when glucose hits 250', 'Step 2: CHECK K+ BEFORE insulin — HOLD insulin if K+ < 3.3', 'Step 3: Regular insulin IV drip 0.1 unit/kg/hr', 'Continue IV insulin + dextrose UNTIL ACIDOSIS RESOLVES (not just glucose)', 'May need 6-10L fluids in 24 hours', 'Monitor glucose HOURLY'], mnemonic: 'Fluids FIRST, K+ SECOND, Insulin THIRD — in that order!', icon: '📋' },

    { section: 'diabetes', drugName: 'DKA Resolution Criteria', brandName: '', drugClass: 'Critical Lab Values', purpose: 'ALL must be met before transitioning off IV insulin', facts: ['pH > 7.30', 'Bicarb > 18 mEq/L', 'Anion gap < 12', 'Glucose < 200 mg/dL', 'Transition to SubQ when patient is EATING AND acidosis resolved', 'Continue monitoring closely during transition'], mnemonic: 'pH-Bicarb-Gap-Glucose — ALL four must normalize', icon: '✅' },

    { section: 'diabetes', drugName: 'Dawn vs Somogyi vs Waning', brandName: '', drugClass: 'AM Hyperglycemia Patterns', purpose: 'Check 3 AM glucose to tell them apart', facts: ['Dawn: 3 AM glucose NORMAL, AM high (GH/cortisol surge) → increase PM insulin', 'Somogyi: 3 AM glucose LOW, AM high (rebound) → decrease PM insulin or bedtime snack', 'Waning: PM insulin wears off → high AM → increase PM dose', 'KEY: Check blood glucose at 3 AM to differentiate', 'Somogyi = body overcompensating for nighttime low'], mnemonic: 'Normal 3AM = Dawn | Low 3AM = Somogyi (SO-MO bounce)', icon: '🌅' },

    { section: 'diabetes', drugName: 'Diabetes Complications', brandName: '', drugClass: 'Chronic Complications', purpose: 'Micro and macrovascular damage over time', facts: ['Retinopathy: #1 cause adult blindness (20-74), annual dilated eye exam, laser photocoagulation', 'Nephropathy: #1 cause ESKD, earliest sign = microalbuminuria, ACE inhibitors renoprotective', 'Neuropathy: bilateral stocking-glove pattern, pain WORSE at night, capsaicin cream (Zostrix)', 'Autonomic neuropathy: PAINLESS MI, gastroparesis, hypoglycemia unawareness', 'Cardiovascular: #1 cause of death in diabetics', 'Foot care: inspect daily, no barefoot, no OTC corn removers, trim nails straight across'], mnemonic: 'Eyes, Kidneys, Nerves, Heart, Feet — check them ALL', icon: '🏥' },

    // ═══ THYROID (9 cards) ═══
    { section: 'thyroid', drugName: 'Hypothyroid vs Hyperthyroid', brandName: 'The Mirror', drugClass: 'Thyroid Comparison', purpose: 'Everything is opposite — slow vs fast', facts: ['Hypo: TSH HIGH, T3/T4 LOW, everything SLOW — bradycardia, constipation, cold intolerance, weight gain, fatigue', 'Hyper: TSH LOW, T3/T4 HIGH, everything FAST — tachycardia, diarrhea, heat intolerance, weight loss, anxiety', 'Hypo unique: myxedema, dry/coarse skin, goiter', 'Hyper unique: exophthalmos (Graves\'), tremor, finger clubbing', 'Hashimoto\'s = autoimmune → hypothyroidism (most common US cause)', 'Goiter foods: broccoli, cabbage, kale, peanuts'], mnemonic: 'HYPO = everything HIBERNATES | HYPER = everything HYPES up', icon: '🪞' },

    { section: 'thyroid', drugName: 'Levothyroxine', brandName: 'Synthroid', drugClass: 'Thyroid Hormone (T4)', purpose: 'Lifelong hypothyroid replacement — the 4S Rule', facts: ['Same time every AM, Separate Ca/Fe by 4 hrs, Stomach empty (30-60 min before food), Signs of toxicity', 'Start LOW dose, increase every 4-6 weeks, full effect up to 8 WEEKS', 'Toxicity = HYPERthyroid signs: HR > 100, weight loss, tremors, insomnia', 'Report pulse > 100 or irregular IMMEDIATELY', 'Interactions: potentiates warfarin (↑bleeding), increases digoxin toxicity', 'Narrow therapeutic index — monitor TSH'], mnemonic: 'LEVO LIVES by the 4S Rule — Same, Separate, Stomach, Signs', icon: '☀️' },

    { section: 'thyroid', drugName: 'Methimazole & PTU', brandName: 'Tapazole / Propylthiouracil', drugClass: 'Antithyroid Drugs', purpose: 'Block thyroid hormone — different pregnancy rules', facts: ['Both: AGRANULOCYTOSIS — fever + sore throat = STOP immediately, check WBC', 'Both: take 4-6 weeks for full effect', 'Methimazole: NOT safe in 1st trimester', 'PTU: 1st trimester ONLY, then switch to methimazole', 'PTU: used in thyroid STORM (blocks synthesis + T4→T3 conversion)', 'PTU BBW: hepatotoxicity — monitor LFTs'], mnemonic: 'PTU = Pregnant Trimester Use (1st only) | Both = Fever+Throat = STOP', icon: '🌡️' },

    { section: 'thyroid', drugName: 'Radioactive Iodine (I-131)', brandName: 'RAI', drugClass: 'Thyroid Ablation', purpose: 'Destroys overactive thyroid permanently', facts: ['ABSOLUTE CI in pregnancy', 'Radiation precautions: separate utensils, flush 2x, 2 weeks', 'Patient often becomes hypothyroid after → lifelong Synthroid', 'Avoid close contact with children/pregnant women', 'Usually ONE dose needed', 'Requires iodine restriction 2 weeks prior (RAIU test)'], mnemonic: 'I-131 = I destroy the thyroid PERMANENTLY', icon: '☢️' },

    { section: 'thyroid', drugName: 'Thyroid Storm', brandName: 'PIBD Protocol', drugClass: 'Thyroid Emergency', purpose: 'Life-threatening — ORDER MATTERS', facts: ['Fever > 104°F, HR > 140 (can be 180+), delirium, seizures, coma', 'NO ASPIRIN (displaces thyroid hormone → worse) → Use TYLENOL', 'P = PTU FIRST (blocks synthesis + T4→T3 conversion)', 'I = Iodine (SSKI/Lugol\'s) — 1 HOUR after PTU', 'B = Beta-blocker (propranolol) — control HR', 'D = Dexamethasone — blocks T4→T3', 'Also: O2, cardiac monitor, IV fluids, ICU, cool/quiet room'], mnemonic: 'PIBD = Panic In the Body\'s Decay — PTU always FIRST', icon: '🚨' },

    { section: 'thyroid', drugName: 'Post-Thyroidectomy', brandName: '', drugClass: 'Post-Op Nursing', purpose: '#1 risk = HYPOCALCEMIA from parathyroid damage', facts: ['Chvostek sign: tap facial nerve → facial twitch', 'Trousseau sign: inflate BP cuff → hand spasm (carpopedal)', 'Keep at bedside: IV calcium gluconate, TRACH kit, O2, SUCTION', 'Position: Semi-Fowler\'s, avoid neck FLEXION', 'Assess q2h x 24hr: bleeding, breathing, swelling, vitals', 'Laryngeal stridor = airway EMERGENCY', 'Check behind neck for blood (pools posteriorly)'], mnemonic: 'Chvostek = Cheek twitch | Trousseau = Tourniquet test', icon: '✂️' },

    { section: 'thyroid', drugName: 'Myxedema Coma', brandName: '', drugClass: 'Hypothyroid Emergency', purpose: 'Severe hypothyroidism → coma, hypothermia, death', facts: ['Triggers: infection, cold exposure, trauma', 'PASSIVE rewarming ONLY — NO heating pads (vasodilation = CV collapse)', 'IV levothyroxine (NOT oral — paralytic ileus won\'t absorb it)', 'IV corticosteroids', 'May need mechanical ventilation', 'Cardiac monitoring, ICU, VS, daily weights, I&O'], mnemonic: 'Myxedema = cold COMA — warm PASSIVELY, IV Synthroid', icon: '🥶' },

    { section: 'thyroid', drugName: 'Parathyroid Disorders', brandName: '', drugClass: 'Calcium/Phosphate Balance', purpose: 'Hypo = low Ca, tetany | Hyper = high Ca, stones', facts: ['HYPOparathyroid: LOW calcium, HIGH phosphate → tetany, Chvostek, Trousseau → IV calcium gluconate', 'HYPERparathyroid: HIGH calcium, LOW phosphate → "Bones, Stones, Groans, Psychic Moans"', 'Bones = fractures, Stones = kidney stones, Groans = abd pain, Moans = confusion', 'PTH specimen: fasting AND kept on ICE', 'ANY neck surgery = watch for hypocalcemia FIRST'], mnemonic: 'HYPO = calcium crashes, tetany | HYPER = Bones Stones Groans Moans', icon: '🦴' },

    { section: 'thyroid', drugName: 'Exophthalmos / Graves\'', brandName: '', drugClass: 'Graves\' Disease Nursing', purpose: 'Protect the eyes — corneal damage risk', facts: ['Exophthalmos = bulging eyes from Graves\' disease', 'Artificial tears (corneas dry out → ulcer risk)', 'Salt restriction to decrease edema', 'HOB elevated', 'Dark glasses (light sensitivity + eye protection)', 'Eye changes may NOT fully reverse even with treatment'], mnemonic: 'Graves\' eyes BULGE — tears, salt limit, shades, HOB up', icon: '👁️' },

    // ═══ PITUITARY / ADRENAL (9 cards) ═══
    { section: 'pitadrenal', drugName: 'SIADH vs DI', brandName: 'The Water Mirror', drugClass: 'Pituitary Comparison', purpose: 'Too much ADH vs too little ADH', facts: ['SIADH: retains water, Na+ LOW (dilutional), urine CONCENTRATED, UO decreased, weight GAIN', 'DI: loses water, Na+ HIGH, urine DILUTE (SG < 1.005), UO MASSIVE (up to 20 L/day), weight loss', 'SIADH treatment: fluid restrict 800-1000 mL/day, tolvaptan, demeclocycline', 'DI treatment: replace fluids + DDAVP (central DI), HCTZ (nephrogenic DI)', 'SIADH #1 cause: small cell lung cancer', 'Severe SIADH (Na < 120): seizure precautions + 3% hypertonic saline'], mnemonic: 'SIADH = Soaking (too wet) | DI = Drying out (too dry)', icon: '💧' },

    { section: 'pitadrenal', drugName: 'Desmopressin', brandName: 'DDAVP', drugClass: 'Synthetic ADH', purpose: 'Replaces ADH for Diabetes Insipidus', facts: ['For Diabetes INSIPIDUS (water, not sugar!)', 'Watch for WATER INTOXICATION (hyponatremia)', 'Monitor: urine SG, I&O, daily weight, Na+', 'Also used for hemophilia A and bedwetting (von Willebrand\'s)', 'Routes: intranasal, IV, or PO', 'Central DI = responds to DDAVP | Nephrogenic DI = does NOT'], mnemonic: 'DDAVP = Drug for Diabetes Insipidus And Vasopressin', icon: '💧' },

    { section: 'pitadrenal', drugName: 'Acromegaly & GH', brandName: 'Somatropin / Octreotide', drugClass: 'Growth Hormone Disorders', purpose: 'Excess GH in adults = acromegaly, deficiency = dwarfism', facts: ['Acromegaly: enlarged hands/feet/face, carpal tunnel, sleep apnea, hyperglycemia', 'Treatment: hypophysectomy (transsphenoidal), octreotide (reduces GH)', 'Post-hypophysectomy: HOB 30°, no teeth brushing x10 days, no coughing/sneezing/straining', 'Watch for CSF leak: glucose-positive clear nasal drainage, halo sign → meningitis risk', 'Lifelong hormone replacement needed after surgery', 'Somatropin (GH replacement): SubQ in EVENING, mimics natural release'], mnemonic: 'Acromegaly = ACROss the body everything GROWS', icon: '💪' },

    { section: 'pitadrenal', drugName: 'Cushing\'s vs Addison\'s', brandName: 'Too Much vs Too Little Cortisol', drugClass: 'Adrenal Comparison', purpose: 'Mirror image — cortisol excess vs deficiency', facts: ['Cushing\'s: cortisol HIGH, glucose HIGH, Na HIGH, K LOW, BP HIGH, immunosuppressed', 'Cushing\'s look: moon face, buffalo hump, trunk obesity, purple striae, hirsutism', 'Addison\'s: cortisol LOW, glucose low, Na LOW (salt craving), K HIGH, BP LOW', 'Addison\'s look: bronze skin (PRIMARY only — ACTH stimulates melanocytes)', 'Iatrogenic Cushing = MOST COMMON form (from long-term prednisone)', 'Cushing Disease vs Syndrome: Disease = pituitary ACTH | Syndrome = any cause'], mnemonic: 'Cushing = Cortisol EXCESS (fat, sugar, salt UP) | Addison = All DOWN', icon: '⚖️' },

    { section: 'pitadrenal', drugName: 'Addison\'s Treatment', brandName: 'Hydrocortisone / Fludrocortisone', drugClass: 'Adrenal Replacement', purpose: 'Lifelong steroid replacement — NEVER stop abruptly', facts: ['Hydrocortisone (Solu-Cortef): replaces BOTH gluco + mineralocorticoid, take AM with food', 'SE: Cushing-like if too much, hyperglycemia, immunosuppression, masks fever', 'Fludrocortisone (Florinef): mineralocorticoid only — SE: HTN, edema, hypokalemia', 'NEVER stop steroids abruptly → adrenal crisis', 'Stress dosing: double/triple during illness/surgery/trauma', 'MedicAlert bracelet = NON-NEGOTIABLE', 'Addisonian crisis = IV hydrocortisone + NS immediately'], mnemonic: 'NEVER stop steroids cold turkey — Addisonian crisis kills', icon: '💊' },

    { section: 'pitadrenal', drugName: 'Cushing\'s Treatment Drugs', brandName: 'Ketoconazole / Mitotane / Mifepristone', drugClass: 'Cortisol-Lowering Agents', purpose: 'Each drug works differently — know the unique SE', facts: ['Ketoconazole: inhibits cortisol synthesis, HEPATOTOXIC — monitor LFTs, no alcohol, no antacids', 'Mitotane: DESTROYS adrenal cortex (cytotoxic), severe N/V, TERATOGENIC both genders', 'Mifepristone: blocks cortisol at receptor — labs look worse but patient improves', 'Surgery: adrenalectomy or hypophysectomy', 'Cushing nursing: monitor BP (HTN), glucose (hyper), K+ (hypo)', 'Fever may be MASKED by excess cortisol — assess for infection carefully'], mnemonic: 'Keto = Kills liver | Mito = Murders adrenal | Mife = Masks receptor', icon: '⚗️' },

    { section: 'pitadrenal', drugName: 'Pheochromocytoma', brandName: '', drugClass: 'Adrenal Medulla Tumor', purpose: 'Excess catecholamines — never palpate the abdomen', facts: ['Classic triad: severe HTN + headache + diaphoresis', 'Also: tachycardia, anxiety, tremor', 'NEVER palpate abdomen → triggers catecholamine release → hypertensive crisis', 'Treatment: Alpha-blocker FIRST (phenoxybenzamine), THEN beta-blocker, THEN surgery', 'WHY alpha first? Beta alone = unopposed alpha = WORSE crisis', 'Diagnosis: 24-hr urine for catecholamines, VMA, metanephrines'], mnemonic: 'Pheo = DON\'T TOUCH the belly! Alpha FIRST, beta SECOND', icon: '⛔' },

    { section: 'pitadrenal', drugName: 'MgSO4 Toxicity', brandName: 'Magnesium Sulfate', drugClass: 'Toxicity Recognition', purpose: 'Know the progression — DTRs disappear first', facts: ['Uses: eclampsia/pre-eclampsia seizure prevention, torsades de pointes', 'Therapeutic range: 4-7 mEq/L', 'FIRST sign of toxicity: loss of DTRs (7-10 mEq/L)', 'Then: respiratory depression → cardiac arrest', 'Antidote: Calcium gluconate IV (keep at bedside)', 'Check DTRs BEFORE each dose — if absent, HOLD magnesium', 'Hold if respirations < 12/min'], mnemonic: 'MgSO4: Reflexes go, Respirations go, then HEART goes', icon: '🫀' },

    { section: 'pitadrenal', drugName: 'Primary vs Secondary Addison\'s', brandName: '', drugClass: 'Addison\'s Disease Trap', purpose: 'The bronze skin question — only in PRIMARY', facts: ['Primary: adrenal gland destroyed, ACTH HIGH, BRONZE SKIN (ACTH → melanocytes)', 'Secondary: pituitary problem, ACTH LOW, NO bronze skin', 'Symptoms appear when 90% of adrenal cortex destroyed', 'Primary Addison\'s diagnosis: ACTH stimulation test (cortisol doesn\'t rise)', 'Both types need lifelong replacement', 'Dexamethasone suppression test = Cushing\'s diagnosis (not Addison\'s)'], mnemonic: 'PRIMARY = Pigmented (bronze) | SECONDARY = no Skin changes', icon: '🟤' },

    // ═══ RENAL (10 cards) ═══
    { section: 'renal', drugName: 'AKI Types', brandName: 'Prerenal / Intrarenal / Postrenal', drugClass: 'Acute Kidney Injury', purpose: 'Where is the problem? Before, inside, or after the kidney', facts: ['Prerenal: LOW blood flow (hypovolemia, HF, sepsis) — GFR IMPROVES with fluids', 'Intrarenal: actual tissue damage (ATN from ischemia/nephrotoxins) — GFR does NOT improve', 'Postrenal: outflow obstruction (BPH #1, stones, tumors) — remove obstruction', 'Prerenal urine: concentrated (SG > 1.020), Na LOW (kidney holds Na)', 'Intrarenal urine: dilute, Na HIGH (kidney can\'t reabsorb), granular casts', 'Nephrotoxins: contrast dye, aminoglycosides (gentamicin), NSAIDs, heavy metals'], mnemonic: 'Pre = Perfusion | Intra = Injury | Post = Plumbing', icon: '🔍' },

    { section: 'renal', drugName: 'AKI Four Phases', brandName: '', drugClass: 'AKI Progression', purpose: 'Oliguric phase is the danger zone — watch K+', facts: ['Onset (hours-days): injury starts — window to PREVENT', 'Oliguric (8-14 days): UO 100-400 mL/24hr, wastes build up, HYPERKALEMIA', 'K+ > 6-6.5 = EKG changes — cardiac arrest risk', 'Diuretic (1-6 weeks): UO increases, DEHYDRATION + electrolyte loss danger', 'Recovery (up to 12 months): function returns to 70-80%', 'Oliguria: < 400 mL/24hr or < 30 mL/hr | Anuria: < 100 mL/24hr'], mnemonic: 'O-O-D-R: Onset, Oliguric (danger), Diuretic (dehydration), Recovery', icon: '📉' },

    { section: 'renal', drugName: 'CKD Stages & Diet', brandName: '', drugClass: 'Chronic Kidney Disease', purpose: 'Know stages by GFR + the diet restrictions', facts: ['Stage 1: GFR > 90 (damage present, normal GFR)', 'Stage 3: GFR 30-59 (moderate)', 'Stage 5: GFR < 15 = ESRD (needs dialysis/transplant)', 'Normal GFR = 120-130 mL/min', 'Diet: LOW sodium, LOW potassium, LOW phosphorus, moderate protein', 'No salt substitutes (contain K+!), phosphate binders WITH meals', 'Avoid: bananas, oranges, potatoes, dairy, cola'], mnemonic: 'CKD diet: No Salt, No K, No Phos — "SNP" restrictions', icon: '🥗' },

    { section: 'renal', drugName: 'Hemodialysis & AV Fistula', brandName: '', drugClass: 'Renal Replacement Therapy', purpose: 'AV fistula care = high-yield nursing content', facts: ['AV fistula = preferred access (longest lasting)', 'Feel for THRILL (vibration), listen for BRUIT (whooshing) = patent', 'NO BP, NO blood draws, NO IV in that arm', 'No tight clothing, no jewelry, no sleeping on that arm', 'Hand exercises to strengthen fistula', '#1 complication: HYPOTENSION (rapid fluid removal)', 'Disequilibrium syndrome: headache, nausea, confusion (rapid BUN drop)'], mnemonic: 'Thrill and Bruit = GOOD | BP and needles in that arm = BAD', icon: '💪' },

    { section: 'renal', drugName: 'Peritoneal Dialysis', brandName: 'CAPD / APD', drugClass: 'Home Dialysis', purpose: 'Peritoneum as filter — watch for cloudy outflow', facts: ['Warm dialysate to body temp (100°F/37.8°C) before infusing', 'CAPD: 4-5 exchanges/day, continuous, 7 days/week', 'APD: cycler machine during sleep (8-10 hours)', 'CLOUDY outflow = PERITONITIS → notify provider, culture fluid', 'Glucose absorbed from dialysate → hyperglycemia risk', 'Protein loss → increased dietary protein needed, monitor albumin', 'Poor outflow → reposition client, keep bag LOWER than abdomen'], mnemonic: 'Cloudy = infection! Warm the fluid, keep bag LOW', icon: '🫧' },

    { section: 'renal', drugName: 'Kidney Transplant', brandName: '', drugClass: 'Transplant Nursing', purpose: 'Lifelong immunosuppression — know rejection types', facts: ['Hyperacute rejection: within 48 hours → IMMEDIATE removal of donor kidney', 'Acute rejection: 1 week-2 years → increase immunosuppressants', 'Chronic rejection: months-years → conservative, may need dialysis', 'Cyclosporine: same time daily, avoid GRAPEFRUIT (↑levels → nephrotoxicity)', 'Post-op: VS q15min → hourly, UO hourly (> 30 mL/hr), daily weight', 'Teach: avoid crowds/sick people, report ANY illness signs'], mnemonic: 'Hyper = Hours (remove) | Acute = Adjust meds | Chronic = Can\'t fix', icon: '🫀' },

    { section: 'renal', drugName: 'Kidney Stones', brandName: '', drugClass: 'Nephrolithiasis', purpose: 'Strain all urine, push fluids, manage pain', facts: ['Severe flank pain (renal colic) → radiates to groin, hematuria, nausea', 'STRAIN ALL URINE (catch stone for analysis)', 'Fluids: 3 L/day minimum', 'Encourage AMBULATION to promote passage', 'Calcium oxalate = MOST COMMON (avoid spinach, peanuts, chocolate)', 'Uric acid stones: treat with allopurinol | Cystine: captopril', 'ESWL: requires sedation, strain urine after, monitor for bleeding'], mnemonic: 'Strain the pee, drink 3L, walk it out — calcium oxalate #1', icon: '🪨' },

    { section: 'renal', drugName: 'Glomerulonephritis', brandName: 'Post-Strep GN', drugClass: 'Renal Inflammation', purpose: '1-3 weeks after strep → cola-colored urine', facts: ['Post-strep: 1-3 weeks after strep throat', 'COLA-COLORED urine (hematuria)', 'RBC casts, proteinuria', 'Facial/periorbital edema (worse in morning)', 'ASO titer confirms recent strep', 'Treatment: antibiotics for strep, manage symptoms'], mnemonic: 'Strep then COLA urine = Glomerulonephritis', icon: '🥤' },

    { section: 'renal', drugName: 'Nephrotic Syndrome', brandName: '', drugClass: 'Massive Protein Loss', purpose: 'Proteinuria > 3.5g/day → edema everywhere', facts: ['Proteinuria > 3.5 g/day (massive protein loss in urine)', 'Hypoalbuminemia → MASSIVE edema', 'Hyperlipidemia', 'DVT risk (lost antithrombin III in urine)', 'Infection risk (lost immunoglobulins)', 'Compare: GN = blood in urine | Nephrotic = protein in urine'], mnemonic: 'Nephrotic = protein POURING out → edema BALLOONING', icon: '🎈' },

    { section: 'renal', drugName: 'Renal Labs & Diagnostics', brandName: '', drugClass: 'Key Lab Concepts', purpose: 'Creatinine is the gold standard for kidney function', facts: ['Creatinine: ONLY elevated by kidney disease (most specific), 50% function lost before it rises', 'BUN: elevated by dehydration, steroids, infection — less specific', 'Elderly: creatinine may look "normal" despite reduced function (less muscle mass)', 'Halitosis (ammonia breath) = uremia/CKD sign', 'IVP: check IODINE allergy, hold metformin', 'Renal biopsy: prone position, pressure dressing, watch for hemorrhage'], mnemonic: 'Creatinine = kidney ONLY | BUN = many causes | Ammonia breath = uremia', icon: '🔬' },

    // ═══ HEMATOLOGY (12 cards) ═══
    { section: 'hematology', drugName: 'Iron Deficiency Anemia', brandName: 'Ferrous Sulfate', drugClass: 'Microcytic Anemia', purpose: 'Most common anemia — spoon nails, take with OJ', facts: ['Spoon-shaped nails (koilonychia), cracked mouth corners', 'Labs: low RBC/Hgb/Hct/iron/ferritin, ELEVATED TIBC', 'Oral iron: empty stomach, 30 min before meals, WITH vitamin C (OJ)', 'Avoid antacids/calcium with iron, straw for liquid (teeth staining)', 'Black stools = NORMAL (expected)', 'Continue iron 2-3 months AFTER Hgb normalizes', 'IM: Z-track method, do NOT massage'], mnemonic: 'Iron + OJ = best friends | Black poop = expected | Continue 2-3 months extra', icon: '🥄' },

    { section: 'hematology', drugName: 'B12 & Folate Deficiency', brandName: '', drugClass: 'Macrocytic Anemias', purpose: 'B12 = neuro symptoms, Folate = NO neuro symptoms', facts: ['B12 (pernicious anemia): no intrinsic factor → NEUROLOGICAL symptoms (numbness, balance, memory)', 'B12 treatment: deep IM injections, monthly, LIFELONG if pernicious', 'Folate: alcoholism #1 cause, same as B12 but NO neuro symptoms', 'DANGER: high-dose folate MASKS B12 deficiency — blood improves but neuro damage continues!', 'ALWAYS check B12 first before treating folate deficiency', 'Both = macrocytic (elevated MCV = large RBCs)'], mnemonic: 'B12 = Brain damage (neuro) | Folate = NO neuro | Always check B12 FIRST', icon: '🧠' },

    { section: 'hematology', drugName: 'Sickle Cell Disease', brandName: '', drugClass: 'Hemolytic Anemia', purpose: 'Genetic HbS — vaso-occlusive crisis is the hallmark', facts: ['Genetic HbS, diagnosed at birth, Hgb electrophoresis confirms', 'Vaso-occlusive crisis: SEVERE pain from sickling → organ damage', 'Crisis triggers: dehydration, infection, cold, stress, high altitude, low O2', 'Crisis nursing: IV fluids, O2, pain management (don\'t undertreat!), WARM packs (not cold)', 'INFECTION = #1 cause of DEATH', 'Acute chest syndrome: fever + chest pain + cough + dyspnea', 'Treatment: hydroxyurea (increases fetal hemoglobin), hydration'], mnemonic: 'Sickle = PAIN crisis + INFECTION kills | Hydrate + Warm + O2', icon: '🫁' },

    { section: 'hematology', drugName: 'Thalassemia & Aplastic', brandName: '', drugClass: 'Special Anemias', purpose: 'Thalassemia = NO iron | Aplastic = pancytopenia', facts: ['Thalassemia: genetic (Mediterranean), defective hemoglobin', 'Thalassemia treatment: transfusions + chelation (deferoxamine)', 'NEVER give iron in thalassemia (already overloaded!)', 'Aplastic: bone marrow failure → PANCYTOPENIA (all cells low)', 'Aplastic: elevated serum iron (not being used), yellow/fatty marrow', 'Aplastic treatment: bone marrow transplant, immunosuppressants', 'Untreated aplastic: median survival 3-6 months'], mnemonic: 'Thalassemia = Too much iron already! | Aplastic = All cells GONE', icon: '🩸' },

    { section: 'hematology', drugName: 'Polycythemia', brandName: '', drugClass: 'Too Many RBCs', purpose: 'Thick blood → clot risk — phlebotomy is treatment', facts: ['Too many RBCs → hyperviscosity → clot/stroke risk', 'Signs: HTN, headache, visual changes, ruddy (red) complexion, splenomegaly', 'ITCHING after warm bath = classic sign (histamine release)', 'JAK2 mutation (polycythemia vera)', 'Treatment: PHLEBOTOMY (remove blood to reduce viscosity)', 'Opposite of anemia — too MUCH is the problem'], mnemonic: 'Poly = too many → thick blood → itchy after bath → drain it out', icon: '🔴' },

    { section: 'hematology', drugName: 'DIC', brandName: 'Disseminated Intravascular Coagulation', drugClass: 'Clotting + Bleeding', purpose: 'Uses up all clotting factors — everything is backwards', facts: ['Clotting AND bleeding at the same time', 'Labs: PT/aPTT HIGH, D-dimer HIGH, fibrinogen LOW, platelets LOW', 'Memory: everything that should be low is HIGH, everything that should be high is LOW', 'Triggers: eclampsia, abruption, gram-negative sepsis, burns, head injury, leukemia', 'Treatment: treat the CAUSE first, then O2, IV fluids, FFP + cryo + platelets', 'Heparin = controversial (patient already bleeding)'], mnemonic: 'DIC = Death Is Coming if you don\'t fix the CAUSE', icon: '💀' },

    { section: 'hematology', drugName: 'HIT', brandName: 'Heparin-Induced Thrombocytopenia', drugClass: 'Drug Reaction', purpose: 'Heparin causes platelets to DROP and paradoxical CLOTTING', facts: ['Immune reaction to heparin → platelets drop + paradoxical CLOTTING', 'STOP ALL heparin immediately (including flushes!)', 'Switch to direct thrombin inhibitor (argatroban, bivalirudin)', 'NEVER give heparin again to this patient', 'Check platelets q2-3 days while on heparin', 'Platelets drop but patient CLOTS (not bleeds)'], mnemonic: 'HIT = Heparin Is Terrible for this patient — STOP everything', icon: '🛑' },

    { section: 'hematology', drugName: 'Blood Transfusion Protocol', brandName: '', drugClass: 'Transfusion Safety', purpose: 'Two nurses verify, stay first 15 min, NS only', facts: ['TWO nurses verify: patient ID, blood type, Rh, expiration', 'Use large-bore IV (18-gauge), 0.9% NS ONLY (never dextrose!)', 'Start slow — stay with patient first 15-30 min', 'VS: every 5 min for first 15 min, then q15min until complete', 'Infuse over 2-4 hours per unit', 'IF REACTION: STOP → remove blood tubing → NEW NS tubing → notify → send bag to lab', 'Autologous transfusion = client\'s own blood (safest option)'], mnemonic: '2 nurses, 18-gauge, NS only, STAY 15 min, STOP if reaction', icon: '🩸' },

    { section: 'hematology', drugName: 'Transfusion Reactions', brandName: '', drugClass: 'Reaction Types', purpose: 'Know the key sign for each reaction type', facts: ['Acute Hemolytic: LOW BACK PAIN + impending doom — MOST DANGEROUS, within 2 min', 'Febrile: fever/chills — MOST COMMON, within 2 hours', 'Mild Allergic: HIVES (urticaria) — antihistamines, may restart', 'Anaphylactic: dyspnea, wheezing, shock — epinephrine', 'Circulatory Overload: CRACKLES + JVD + HTN — diuretics, sit up', 'TS-GVHD: 1-2 weeks after, 90% mortality — use IRRADIATED blood to prevent', 'ALL reactions: STOP transfusion FIRST'], mnemonic: 'Back pain = Hemolytic | Hives = Allergic | Crackles = Overload | Always STOP first', icon: '⚠️' },

    { section: 'hematology', drugName: 'Anticoagulants', brandName: 'Heparin / Enoxaparin / Warfarin', drugClass: 'Blood Thinners', purpose: 'Know monitoring labs and antidotes for each', facts: ['Heparin: monitor aPTT (1.5-2.5x normal), antidote = protamine sulfate', 'Enoxaparin: SubQ abdomen ONLY, do NOT expel air, do NOT rub, NO routine monitoring', 'Warfarin: monitor INR (goal 2-3), antidote = vitamin K, takes 3-5 DAYS to work', 'Warfarin Category X — NEVER in pregnancy (teratogenic)', 'Warfarin: keep vitamin K intake CONSISTENT (don\'t suddenly change)', 'FFP for active severe warfarin bleeding (immediate factor replacement)'], mnemonic: 'Heparin = aPTT + Protamine | Warfarin = INR + Vitamin K', icon: '💊' },

    { section: 'hematology', drugName: 'Neutropenia Protocols', brandName: '', drugClass: 'Infection Prevention', purpose: 'Fever in neutropenic patient = MEDICAL EMERGENCY', facts: ['ANC < 1000 = neutropenic', 'Fever in neutropenic patient → cultures + antibiotics within 1 HOUR', 'Protective isolation, hand hygiene, no fresh flowers/fruits', 'No rectal temps, no IM injections', 'Thrombocytopenia: petechiae = hallmark, soft toothbrush, electric razor', 'Platelet transfusion when < 20,000', 'Felty syndrome: RA + neutropenia → recurrent infections'], mnemonic: 'Neutropenic + Fever = 1 HOUR to antibiotics — EMERGENCY', icon: '🦠' },

    { section: 'hematology', drugName: 'Leukemia & Lymphoma', brandName: '', drugClass: 'WBC Cancers', purpose: 'Hodgkin = Reed-Sternberg | Leukemia types by age', facts: ['Hodgkin: Reed-Sternberg cells (gold standard), single node, radiation + chemo', 'Non-Hodgkin: NO Reed-Sternberg, extranodal sites, chemo + rituximab', 'AML: 80% of ADULT leukemias', 'ALL: most common in CHILDREN', 'CML: Philadelphia chromosome (BCR-ABL), treat with imatinib (Gleevec)', 'CLL: most common leukemia in adults overall', 'Tumor Lysis Syndrome: massive cell death → hyperK, hyperPhos, hyperUric, hypoCa'], mnemonic: 'Hodgkin = Reed-Sternberg | AML = Adult | ALL = Little kids | CML = Philadelphia', icon: '🔬' },

    // ═══ QUICK REFERENCE (4 cards) ═══
    { section: 'quickref', drugName: 'Antidote Table', brandName: '', drugClass: 'Emergency Antidotes', purpose: 'Match each toxicity to its reversal agent', facts: ['Heparin → Protamine sulfate', 'Warfarin → Vitamin K (phytonadione)', 'MgSO4 → Calcium gluconate', 'Benzodiazepines → Flumazenil', 'Opioids → Naloxone (Narcan)', 'Acetaminophen → Acetylcysteine (Mucomyst)', 'Digoxin → Digibind (digoxin immune fab)', 'Iron → Deferoxamine', 'Beta-blockers → Glucagon', 'Methotrexate → Leucovorin'], mnemonic: 'Every poison has a partner — know all 10 pairs', icon: '🧪' },

    { section: 'quickref', drugName: 'Critical Lab Values', brandName: '', drugClass: 'Panic Values', purpose: 'Know when to call the provider STAT', facts: ['K+: 3.5-5.0 | Panic: < 3.0 (arrhythmia), > 6.0 (cardiac arrest)', 'Na+: 136-145 | Panic: < 120 (seizures), > 160 (confusion)', 'Ca2+: 8.5-10.5 | Panic: < 7.0 (tetany), > 13.0 (cardiac)', 'Mg2+: 1.5-2.5 | Panic: > 7.0 (DTR loss)', 'Glucose: 70-100 | Panic: < 50 (coma), > 400 (DKA/HHS)', 'INR: 0.8-1.2 | > 4.0 = bleeding risk', 'Creatinine > 4.0 = renal failure'], mnemonic: 'K and Ca kill the heart | Na causes seizures | Mg kills reflexes', icon: '📊' },

    { section: 'quickref', drugName: 'Diabetes Numbers', brandName: '', drugClass: 'Glucose Thresholds', purpose: 'Every critical glucose level and what to do', facts: ['< 70 = HYPOGLYCEMIA → Rule of 15', '70-100 = normal fasting', '100-125 = prediabetes', '> 126 fasting = diabetes (confirm on 2 separate days)', '> 240 = test urine for ketones', '> 250 = do NOT exercise, notify provider if sick', '> 300 + ketones = EMERGENCY', '> 600 = HHS threshold', 'A1C goal: < 7% | A1C > 6.5% = diagnostic'], mnemonic: '70-100-126-240-250-300-600 — each level = different action', icon: '🔢' },

    { section: 'quickref', drugName: 'Hemostasis & Clotting', brandName: '', drugClass: 'Coagulation Framework', purpose: '3 requirements + 5 stages + vitamin K', facts: ['3 Requirements: Platelets + von Willebrand factor + Clotting factors (liver + vitamin K)', '5 Stages: vessel spasm → platelet plug → coagulation cascade → clot retraction → dissolution', 'Vitamin K activates: Prothrombin (II), VII, IX, X, Protein C, Protein S', 'Protein C + S = natural anticoagulants (deficiency = hypercoagulable)', 'Heparin works by accelerating Antithrombin III', 'Von Willebrand disease: treat with DDAVP (releases stored vWF)', 'Hypercoagulable states: pregnancy, OCP, immobility, cancer, post-surgical'], mnemonic: 'Platelets + vWF + Factors = clot | Vitamin K activates 2-7-9-10', icon: '🩹' },
  ]
};
